data:
  image_size: 512


vae:
  model_name: 'sdvae_f8d4'
  model_dir: vae
  downsample_ratio: 8
  embed_dim: 4



model:
  model_type: PixelHacker

  in_channels: 9
  out_channels: 4

  attention_head_dim: 8
  cross_attention_dim: 768

  encoder_hid_dim: 3072
